spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
  profiles:
    active: dev
  application:
    name: "Course Api Server"
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/course?useTimezone=true&serverTimezone=UTC&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  flyway:
    check-location: true
    baselineOnMigrate: true
    locations: classpath:db/migration

server:
  port: 9090