CREATE TABLE TOPIC (
  ID            INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME         VARCHAR(512) NOT NULL,
  DESCRIPTION         VARCHAR(512) NOT NULL,
  CREATED_AT    DATETIME NOT NULL,
  UPDATED_AT    DATETIME
);
